package digitalparkingsystem;

import java.util.UUID;

public abstract class ParkingSpot {
	private String id; // Auto-Generated by UUID
	private boolean isOccupied;
	private VehicleType type;

	public ParkingSpot(VehicleType type) {
		this.id = UUID.randomUUID().toString();
		this.isOccupied = false;
		this.type = type;
	}

	public void occupy() {
		this.isOccupied = true;
	}

	public void free() {
		this.isOccupied = false;
	}
	
	//Getters and Setters

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public boolean isOccupied() {
		return isOccupied;
	}

	public void setOccupied(boolean isOccupied) {
		this.isOccupied = isOccupied;
	}

	public VehicleType getType() {
		return type;
	}

	public void setType(VehicleType type) {
		this.type = type;
	}

}
